version: "2"
linters:
  enable:
    - copyloopvar
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - bodyclose
    - nilerr
    - errorlint
formatters:
  enable:
    - gofmt
